exclude: ^(screenshots)/
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: check-yaml
    -   id: check-toml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: mixed-line-ending

-   repo: https://github.com/PyCQA/isort
    rev: 6.0.1
    hooks:
    -   id: isort
        files: .

-   repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
    -   id: black
        files: .

-   repo: https://github.com/tox-dev/pyproject-fmt
    rev: v2.6.0
    hooks:
    -   id: pyproject-fmt

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.9
    hooks:
    -   id: ruff
